### ISSUE TITLE
updating flavor for a cloud doesn't work

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#164] opened 2019-03-15 02:22 UTC
This is on csv2-dev2. 
When trying to select a specific flavor for a cloud, click update, the following appears and the new flavor is not selected:
```
Request Method: | POST
-- | --
https://csv2-dev2.heprc.uvic.ca/cloud/update/
2.0.5
ProgrammingError
(_mysql_exceptions.ProgrammingError) (1146, "Table 'csv2.kill_retire_priority_list' doesn't exist") [SQL: 'update csv2_vms as cv left outer join (select * from kill_retire_priority_list) as kpl on cv.vmid=kpl.vmid set retire=1, updater="cloud_views.py:1421:r1" where kpl.vmid is not null;'] (Background on this error at: http://sqlalche.me/e/f405)
/usr/lib64/python3.6/site-packages/MySQLdb/connections.py in query, line 277
/usr/bin/python3
3.6.5
['/opt/cloudscheduler/web_frontend/cloudscheduler',  '/usr/lib64/python36.zip',  '/usr/lib64/python3.6',  '/usr/lib64/python3.6/lib-dynload',  '/usr/lib64/python3.6/site-packages',  '/usr/lib/python3.6/site-packages',  '/']
Thu, 14 Mar 2019 19:17:31 -0700
```

**Comment by crlb** [comment] 2019-03-15 17:44
Not a bug; incomplete code. Scaling of resources (cores/ram) was changed to prioritize idle VMs over old ones. This change required updates to view_utils.py and to view_vm_kill_retire_priority_list_idle. Both these changes were applied to stable-2.2.1 (hot fix) on csv2 and merged back to the dev branch on dev and dev2. On the development machines, the python code update was activated on the next httpd restart but the view update was not applied, resulting in the error.

**Closed by crlb** 2019-03-15 17:44 UTC
Labels: invalid
