### ISSUE TITLE
retire of total of all VMs  in project doesn't retire all

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#294] opened 2020-04-14 15:31 UTC
2.6.1: 
For a project one can expand the Total row, click on the 3 dashes to get a list of all VMs. From there one can select all VMs and then click on retire.
The expected behavior is that all VMs that were selected (on all clouds for this project) get retired.
What happens however is that only the VMs on the project that is first in the list get retired.
On csv2a for belle:  Total of all VMs shows VMs on all Belle-II clouds, selecting all and click retire results in VMs on on arbutus get retired.

**Comment by colsond** [comment] 2020-04-14 15:41
Sounds like a bug in the javascript submission- My guess is that when opening the overlay it passes along some session variables for the relevant cloud to use when submitting and that those values are wrong for the totals row. I'll have to investigate further.

**Comment by MarcusEbert** [comment] 2020-04-14 18:22
duplicate of #243 it seems...

**Comment by colsond** [comment] 2021-07-12 17:32
Closing as duplicate of #243

**Closed as completed by colsond** 2021-07-12 17:32 UTC
Labels: bug
