### ISSUE TITLE
End time of plot is last refresh time, not current time

### ISSUE THREAD

**Issue by TristanSullivan** [hep-gc/cloudscheduler#393] opened 2023-04-04 21:01 UTC
When a quantity is plotted on the web interface, the end time of the plot is the time the page was last refreshed, not the current time.

**Comment by colsond** [comment] 2023-04-27 15:58
While i was working on the multi-trace plotting issues it became clear that the issue here isn't the time window being submitted for the plot but rather an error introduced in my ssl influxdb implementation. The root cause was that the plot refreshes were all actually failing due to a CORS error (Cross origin resource sharing). The browser first sends an OPTION request to influx which returns a payload that includes a header that allows this cross origin sharing for the purpose of plotting. However there was an error in the url used to refresh the plot which caused the return payload of the OPTION to be missing the required headers so the browser decided there was some bad behavior going on and blocked the request for new trace data. This should be fixed on the dev server and will make it's way into the next release.

**Closed as completed** 2023-12-14 21:34 UTC
